[package]
name = "lazyp4"
description = "A terminal UI for Perforce, in the style of lazygit"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "lazyp4"
path = "src/main.rs"

[dependencies]
p4 = { path = "../p4" }
ratatui = "0.30.2"
crossterm = "0.29.0"
